kafka:
  topic_name: topic_air_quality_pollution_data # Name of the Kafka topic to which the producer will send data
  bootstrap_servers: kafka:9092 # Kafka broker address

streamer:
  interval_in_seconds: 2.0 # Interval in seconds for the data streamer to fetch new data
  is_infinite: false # If true, the streamer will run indefinitely; if false, it will stop after fetching data once

database:
  host: mongodb # Hostname of the MongoDB server
  port: 27017 # Port on which MongoDB is running
  name: air_quality_pollution_db # Name of the MongoDB database
  collection_name: air_quality_pollution_data # Name of the MongoDB collection where data will be stored

app:
  logs:
    folder: /tmp # folder inside the container where the logs shall be stored - make sure this matches the settings in the docker compose file
    filemode: w # "a" for append, "w" for overwrite
